version: "3.9"
services:
  database:
    build:
      context: database
      dockerfile: Dockerfile
    image: murilochianfa/rinha-crebito-cpp-database:latest
    container_name: rinha-database
    hostname: database
    restart: unless-stopped
    pull_policy: always
    network_mode: host
    stdin_open: false
    tty: false
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "healthy"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "300MB"

  app-northbound: &app
    build:
      context: app
      dockerfile: Dockerfile
    image: murilochianfa/rinha-crebito-cpp-app:latest
    container_name: rinha-app-northbound
    hostname: app-northbound
    restart: unless-stopped
    pull_policy: always
    environment:
      - API_PORT=8848
    network_mode: host
    depends_on:
      - database
    stdin_open: false
    tty: false
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "100MB"

  app-southbound:
    <<: *app
    container_name: rinha-app-southbound
    hostname: api-southbound
    environment:
      - API_PORT=8849

  loadbalancer:
    build:
      context: loadbalancer
      dockerfile: Dockerfile
    image: murilochianfa/rinha-crebito-cpp-loadbalancer:latest
    container_name: rinha-loadbalancer
    hostname: loadbalancer
    restart: unless-stopped
    pull_policy: always
    network_mode: host
    depends_on:
      - app-northbound
      - app-southbound
    stdin_open: false
    tty: false
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

